project:
  type: book

book:
  title: "When Love Hurts"
  author: "Gloria Aiyebogun"
  date: "11/30/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_one.qmd
    - chapter_two.qmd
    - chapter_three.qmd
    - chapter_four.qmd
    - chapter_five.qmd
    - chapter_six.qmd
    - chapter_seven.qmd
    - chapter_eight.qmd
    - chapter_nine.qmd
    - about_author.qmd
    - references.qmd

citeproc: true
bibliography: references.bib
csl: apa.csl     # <-- This specifies the APA style format

format:
  html:
    theme: [cosmo, styles.scss] # Styles for the website output
  pdf:
    # Use scrbook for professional, double-sided printing layout
    documentclass: book
    papersize: letter
    
    # 1. Font Selection (Requires the font to be installed or use a common package)
    
    fontsize: 11pt                # Base Size
    
    # 2. Including the necessary LaTeX packages
    # We need titlesec for the chapter format and the LaTeX font packages
    include-in-header: 
      file: custom-chapter-style.tex
  epub:
    # Use the same custom SCSS file for the EPUB styling
    theme: [cosmo, styles.scss] 
    # Important EPUB specific setting:
    title-page: true 
    # You might want a different toc depth for EPUB vs. HTML
    toc-depth: 3

    cover-image: cover.png



